//
//  MyClass.m
//  fiftyWays
//
//  Created by chenshalev on 19/09/2025.
//

#import "MyClass.h"

NS_ASSUME_NONNULL_BEGIN

/*
 
 This class is the destination class (or the callee)
 It exposes class methods and instance methods that fit the code generated by the tool
 Use the tool to generate the calling function from either objc (ObjCCaller) or swift (SwiftCaller)

 
 */

@implementation MyClass


// replace this with the implementation from the tool
-(id) methodName {
    NSLog(@"method was triggered");
    return @"ack";
}

@end

NS_ASSUME_NONNULL_END
